### PR TITLE
Added AWS Session Token support (needed when run on Lambda)

### PR DESCRIPTION
**Pull request by nsaliu**
Added AWS Session Token support (needed when run on Lambda).

This is only a draft/suggestion, because I had to add the retrieval of that env var in order to make it works on Lambda function.

### CODE REVIEW

**Comment by cviebrock** [comment]
I'm not familiar with AWS.  I'm assuming `AWS_SESSION_TOKEN` is only available in an env variable?  I feel it would be nicer if the Factory pulled the value from the config, and the config read it from the environment ... if that's possible.

**Comment by nsaliu** [comment]
> I'm not familiar with AWS. I'm assuming `AWS_SESSION_TOKEN` is only available in an env variable? I feel it would be nicer if the Factory pulled the value from the config, and the config read it from the environment ... if that's possible.

Yes, this var is auto generated (https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_use-resources.html) and is available only as an env var.
I've apply you CR ;)

**Comment by nsaliu** [comment]
@cviebrock any news about this PR? 😄

**Review by cviebrock — APPROVED** [review]

**Comment by nsaliu** [comment]
@cviebrock I found this interesting discussion about my change in your code :+1:  https://github.com/laravel/laravel/pull/5138
Hope will be helpful for the future!

**Pull request merged**
