### PR TITLE
Add index-exists console command

### PR DESCRIPTION
**Pull request by nsaliu**
Hi @cviebrock !
Are you interested in some `utility commands` like this?

For my release pipeline I've created a few of them, and if you are interested I can add also the others.

Let me know,
Thank you!

### CODE REVIEW

**Comment by cviebrock** [comment]
Hi @nsaliu !

Absolutely!  If you'd like to make PRs for all of your console commands, I'd be happy to add them to the package.  I'm sure others would find them useful as well!

**Comment by cviebrock** [comment]
I've merged this PR, but I'll wait until you add your others before tagging a new release.

Thanks again!

**Comment by nsaliu** [comment]
Ok thank you!

In the next days I'll add other commands :+1:

**Comment by nsaliu** [comment]
@cviebrock after merging all the PRs that you want, I will update the readme - tell me when you are ready

**Comment by cviebrock** [comment]
Merged all the PRs.  If you'd like to update the readme, that would be great.  I can then give everything a once-over before tagging a new release.

Thanks again!

**Comment by nsaliu** [comment]
Sure, I think tomorrow I'll update the readme. 

Thank you!

**Pull request merged**
